config/routes.rb
# frozen_string_literal: true

# Rails plumbing.
Rails.application.routes.draw do
  get 'publications/suggestions'

  match '/hello', as: 'hello_page', to: 'hello#index', via: :get
  match '/filtered/search', as: 'filtered_search', to: 'filtered_search#index', via: :get
  match '/names/search', as: 'name_search', to: 'names#index', via: :get
  match '/name/check', as: 'name_check', to: 'name_check#index', via: :get
  match '/name/check/search', as: 'name_check_search',
                            to: 'name_check#index', via: :get
  match '/name/:id', as: 'show_name', to: 'names#show', via: :get
  match '/search', as: 'search', to: 'names#index', via: :get
  match '/name/history/:id', as: 'name_history', to: 'names#history', via: :get
  match '/names/search/within/taxon/:id/summary',
        as: 'names_search_within_taxon_summary',
        to: 'names/search/within/taxon/summary#index',
        via: :get
  get '/index.*', to: 'names#index'
  match '/names/advanced', as: 'names_advanced_search',
                           to: 'advanced_names#index', via: :get
  match '/names/:id', as: 'show_names', to: 'names#show', via: :get
  match '/taxonomy/search', as: 'taxonomy_search',
                            to: 'taxonomy#index', via: :get
  match '/publications/suggestions/:search_term', as: 'publication_suggestions', to: 'publications#suggestions', via: :get
  get '/settings', as: 'settings', to: 'settings#index'
  get '/settings/index', as: 'settings_index', to: 'settings#index'


  # Editor Links Section
  # Allow from browser, so 'get', for bookmarking.
  match '/I-am-an-editor', as: 'I_am_an_editor', to: 'preferences#editor_switch', via: [:get], defaults: { switch: 'editor', value: 'on' }
  match '/i-am-an-editor', as: 'i_am_an_editor', to: 'preferences#editor_switch', via: [:get], defaults: { switch: 'editor', value: 'on' }
  # Use as hidden link, needs to be a post to avoid apparent auto getting.
  match '/i-am-an-editor-post', as: 'i_am_an_editor_post', to: 'preferences#editor_switch', via: [:post], defaults: { switch: 'editor', value: 'on' }
  # Use "post" and indicate this is a post for consistency.
  match '/i-am-not-an-editor-post', as: 'i_am_not_an_editor_post', to: 'preferences#editor_switch', via: [:post], defaults: { switch: 'editor', value: 'off' }
  # 
  post '/background', to: 'settings#background'

  root to: 'names#index'
  get '*path' => 'names#index'
end

app/controllers/name_check_controller.rb
# frozen_string_literal: true

# Controller
class NameCheckController < ApplicationController
  def index
    @page_title = "Name Check"
    @client_request = Index::ClientRequest.new(search_params)
    @wrapped_search_results = Results.new(@client_request.search_results)
  end

  private

  def search_params
    params.permit(:utf8, :q, :controller, :action, :list_or_tabular, :limit,
                  :show_links)
  end
end

app/views/name_check/index/_debug.html.erb
any type of search? <%= @client_request.any_type_of_search?.to_s %>
<br>
<%= params.inspect %>
<br>
<%= @client_request.params %>
<br>
raw results: <%= @client_request.search_results %>
<% unless @wrapped_search_results.nil? %>
<br> wrapped results present? <%= @wrapped_search_results.present? %>
<br> wrapped results empty? <%= @wrapped_search_results.empty? %>
<br> wrapped results results class? <%= @wrapped_search_results.results.class %>
<br> wrapped results results size? <%= @wrapped_search_results.results.size %>
<% end %>
<br>

app/views/name_check/index/_list_output.html.erb
<% @wrapped_search_results.results.each do |result| %>
  <% unless result.matched_name_full_name.blank? %>
    <% if @client_request.links? %>
      <%= link_to(result.matched_name_full_name, show_name_path(id: result.matched_name_id, search_form: 'names'), title: 'Show name') %>
    <% else %>
      <%= result.matched_name_full_name %>
    <% end %>
    <% if result.matched_name_accepted_taxonomy_accepted? %>
      <span class='red' title='Accepted by APC'><i class="fa fa-check"></i>APC</span>
    <% elsif result.matched_name_accepted_taxonomy_excluded? %>
      <span class='red' title='Excluded by APC'><i class="fa fa-ban"></i>APC</span>
    <% end %>
    <br>
  <% end %>
<% end %>

app/views/name_check/index/_search_form.html.erb
<div id="form-div">
<%= form_tag(name_check_search_path, method: :get) %>
<br>
<textarea rows="15"
          cols="50"
          name='q'
          value="<%= params['q'] %>"
          required
          placeholder="Names to check."
          title="Text area for search terms"><%= params['q'] %></textarea>
<br>
<div id="search-text-area-field-help" class="general-help field-help hidden">
  <div class="hide-this-help-link-container text-align-right"><a href="" class="hide-this-help-link" data-target-id="search-text-area-field-help" title="Hide this help." >x</a></div>
  <ul class="help">
  </ul>
</div>
    <%= radio_button_tag(:list_or_tabular, "tabular", @client_request.tabular?, title: 'Tabular output of matching names') %>
    <%= label_tag(:list_or_tabular_tabular, "Table", title: 'Tabular output - can show more information than list output') %>
<br>
    <%= radio_button_tag(:list_or_tabular, "list", @client_request.list?, title: 'List of matching names') %>
    <%= label_tag(:list_or_tabular_list, "List", title: 'List output - matching names only') %>
<div id="list-or-tabular-field-help" class="general-help field-help hidden">
  <div class="hide-this-help-link-container text-align-right"><a href="" class="hide-this-help-link" data-target-id="list-or-tabular-field-help" title="Hide this help." >x</a></div>
  <ul class="help">
  </ul>
</div>

<hr>
    <%= check_box_tag(:show_links, '1', @client_request.links?, title: name_check_show_links_hover_text) %>
    <%= label_tag(:show_links, "Show with links", title: name_check_show_links_hover_text) %>
<br>
<div id="show-links-field-help" class="general-help field-help hidden">
  <div class="hide-this-help-link-container text-align-right">
    <a href="" class="hide-this-help-link" data-target-id="show-links-field-help" title="Hide this help." >x</a>
  </div>
  <ul class="help">
    <li>Listed names can be plain text, or hyperlinks.
    <li>If links are displayed and followed they will lead to a full page of details for the selected name.
  </ul>
</div>

    <input type="number"
           name="limit"
           title="Number of records per page when details is not checked."
           min="1"
           max="<%= Rails.configuration.default_list_size_limit %>"
           step="1"
           value="<%= params[:limit] || Rails.configuration.default_list_size %>"
           class="form-field"> 
Per page
<br>
<div id="page-limit-field-help" class="general-help field-help hidden">
  <div class="hide-this-help-link-container text-align-right"><a href="" class="hide-this-help-link" data-target-id="page-limit-field-help" title="Hide this help." >x</a></div>
  <ul class="help">
  </ul>
</div>


<input type="submit"
       value="Search"
       class="left-aligned-form-button"
       title="Search the data and retrieve matching records">

</form>
</div>

app/views/name_check/index/_tabular_output.html.erb
<table class="name-check">
  <tr>
    <th class="left-align">Search Term</th>
    <th class="left-align">Matching Name</th>
    <th class="left-align">Census</th>
    <th class="left-align">Matching Name Family</th>
  </tr>
<% @wrapped_search_results.results.each do |result| %>
  <tr>
    <td><%= result.search_term unless result.index.to_i > 1 %></td>
    <td><%= result.matched_name_full_name %></td>
    <td>
        <% if result.matched_name_accepted_taxonomy_accepted? %>
          <span class='red' title='Accepted by APC'><i class="fa fa-check"></i>APC</span>
        <% elsif result.matched_name_accepted_taxonomy_excluded? %>
          <span class='red' title='Excluded by APC'><i class="fa fa-ban"></i>APC</span>
        <% else %>
          &nbsp;
        <% end %>
    </td>
    <td><%= result.matched_name_family_name %></td>
  </tr>
<% end %>
</table>

app/views/name_check/index/_tabular_output_with_links.html.erb
<table class="name-check">
  <tr>
    <th class="left-align">Search Term</th>
    <th class="left-align">Matching Name</th>
    <th class="left-align">Census</th>
    <th class="left-align">Matching Name Family</th>
  </tr>
<% @wrapped_search_results.results.each do |result| %>
  <tr>
    <td><%= result.search_term unless result.index.to_i > 1 %></td>
    <% if result.found? %>
      <td><%= link_to(result.matched_name_full_name, show_name_path(id: result.matched_name_id, search_form: 'names'), title: 'Show name') %></td>
      <td>
        <% if result.matched_name_accepted_taxonomy_accepted? %>
          <span class='red' title='Accepted by APC'><i class="fa fa-check"></i>APC</span>
        <% elsif result.matched_name_accepted_taxonomy_excluded? %>
          <span class='red' title='Excluded by APC'><i class="fa fa-ban"></i>APC</span>
        <% else %>
          &nbsp;
        <% end %>
      </td>
    <% else %>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    <% end %>
    <% if result.found? && result.matched_name_family_name.present? %>
      <td><%= link_to(result.matched_name_family_name, show_name_path(id: result.matched_name_family_name_id, search_form: 'names'), title: 'Show name') %></td>
    <% else %>
      <td>&nbsp;</td>
    <% end %>
  </tr>
<% end %>
</table>